/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.bandtec.lista6.resolucao;

/**
 *
 * @author natanista
 */
public class Elevadores extends javax.swing.JFrame {
    
    Double pesoTotal = 0.0;
    Integer totalPassageiros = 0;
    /**
     * Creates new form Elevadores
     */
    public Elevadores() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
   
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnEntrarHomem = new javax.swing.JButton();
        btnEntrarMulher = new javax.swing.JButton();
        btnEntrarCrianca = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblTotalPassageiros = new javax.swing.JLabel();
        lblPesoTotal = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnEntrarHomem2 = new javax.swing.JButton();
        btnEntrarMulher2 = new javax.swing.JButton();
        btnEntrarCrianca2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblTotalPassageiros2 = new javax.swing.JLabel();
        lblPesoTotal2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        btnEntrarHomem.setText("Entrar Homem");
        btnEntrarHomem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntrarHomemActionPerformed(evt);
            }
        });

        btnEntrarMulher.setText("Entrar mulher");
        btnEntrarMulher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntrarMulherActionPerformed(evt);
            }
        });

        btnEntrarCrianca.setText("Entrar criança");
        btnEntrarCrianca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntrarCriancaActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setText("Total de passageiros no elevador: ");

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setText("Peso total no elevador: ");

        lblTotalPassageiros.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblTotalPassageiros.setText("0");

        lblPesoTotal.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblPesoTotal.setText("0kg");

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("ELEVADOR DIGITAL BUILDING");

        jLabel4.setText("Elevador 1");

        btnEntrarHomem2.setText("Entrar Homem");
        btnEntrarHomem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntrarHomem2ActionPerformed(evt);
            }
        });

        btnEntrarMulher2.setText("Entrar mulher");
        btnEntrarMulher2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntrarMulher2ActionPerformed(evt);
            }
        });

        btnEntrarCrianca2.setText("Entrar criança");
        btnEntrarCrianca2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntrarCrianca2ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel5.setText("Total de passageiros no elevador: ");

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel6.setText("Peso total no elevador: ");

        lblTotalPassageiros2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblTotalPassageiros2.setText("0");

        lblPesoTotal2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblPesoTotal2.setText("0kg");

        jLabel7.setText("Elevador 2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addComponent(jLabel4))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnEntrarMulher)
                                    .addComponent(btnEntrarHomem)
                                    .addComponent(btnEntrarCrianca)))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblPesoTotal))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblTotalPassageiros)))))
                        .addGap(100, 100, 100)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addComponent(jLabel7))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnEntrarMulher2)
                                    .addComponent(btnEntrarHomem2)
                                    .addComponent(btnEntrarCrianca2)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblPesoTotal2))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblTotalPassageiros2))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addComponent(jLabel3)))
                .addContainerGap(134, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnEntrarHomem)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEntrarMulher)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEntrarCrianca)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(lblTotalPassageiros))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(lblPesoTotal)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnEntrarHomem2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEntrarMulher2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEntrarCrianca2)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(lblTotalPassageiros2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(lblPesoTotal2))))
                .addContainerGap(66, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
       public void atualizarPesoTotal(Double peso){
           pesoTotal += peso;
           lblPesoTotal.setText(pesoTotal.toString() + "kg");
       }
    private void btnEntrarHomemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntrarHomemActionPerformed
        atualizarPesoTotal(90.0);
        adicionarPassageiro();
    }//GEN-LAST:event_btnEntrarHomemActionPerformed
    
    public void adicionarPassageiro(){
      totalPassageiros++;
      lblTotalPassageiros.setText(totalPassageiros.toString());
    }
    
    private void btnEntrarMulherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntrarMulherActionPerformed
        atualizarPesoTotal(65.0);
        adicionarPassageiro();
    }//GEN-LAST:event_btnEntrarMulherActionPerformed

    private void btnEntrarCriancaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntrarCriancaActionPerformed
        atualizarPesoTotal(40.0);
       adicionarPassageiro();
       
    }//GEN-LAST:event_btnEntrarCriancaActionPerformed

    private void btnEntrarHomem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntrarHomem2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEntrarHomem2ActionPerformed

    private void btnEntrarMulher2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntrarMulher2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEntrarMulher2ActionPerformed

    private void btnEntrarCrianca2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntrarCrianca2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEntrarCrianca2ActionPerformed

    /**pesoTotal
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the NpesoTotalimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Elevadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Elevadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Elevadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Elevadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Elevadores().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEntrarCrianca;
    private javax.swing.JButton btnEntrarCrianca2;
    private javax.swing.JButton btnEntrarHomem;
    private javax.swing.JButton btnEntrarHomem2;
    private javax.swing.JButton btnEntrarMulher;
    private javax.swing.JButton btnEntrarMulher2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel lblPesoTotal;
    private javax.swing.JLabel lblPesoTotal2;
    private javax.swing.JLabel lblTotalPassageiros;
    private javax.swing.JLabel lblTotalPassageiros2;
    // End of variables declaration//GEN-END:variables
}
