/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.bandtec.lista6.resolucao;

import java.util.concurrent.ThreadLocalRandom;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JProgressBar;

/**
 *
 * @author natanista
 */
public class Lutadores extends javax.swing.JFrame {

    Integer vida1 = 100;
    Integer vida2 = 100;

    /**
     * Creates new form Lutadores
     */
    public Lutadores() {
        initComponents();
        lblProgresso1.setValue(vida1);
        lblProgresso2.setValue(vida2);
        lblVida1.setText(vida1.toString() + "%");
        lblVida2.setText(vida2.toString() + "%");
        removerBotão(btnReiniciar);
        btnReiniciar.setText("");
    }

    /**
     * vida1 -= 10; This method is called from within the constructor to
     * initialize the form. WARNING: Do NOT modify this code. The content of
     * this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblProgresso2 = new javax.swing.JProgressBar();
        lblProgresso1 = new javax.swing.JProgressBar();
        lblVida2 = new javax.swing.JLabel();
        lblVida1 = new javax.swing.JLabel();
        btnConcentrar = new javax.swing.JButton();
        btnApanhar = new javax.swing.JButton();
        lblResultado = new javax.swing.JLabel();
        btnReiniciar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblVida2.setText("0%");

        lblVida1.setText("0%");

        btnConcentrar.setText("Concentrar força");
        btnConcentrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConcentrarActionPerformed(evt);
            }
        });

        btnApanhar.setText("Apanhar");
        btnApanhar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApanharActionPerformed(evt);
            }
        });

        lblResultado.setText("Resultado");

        btnReiniciar.setText("Reiniciar");
        btnReiniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReiniciarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 51));
        jLabel1.setText("CLUBE DA LUTA");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(lblResultado)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnApanhar)
                        .addGap(18, 18, 18)
                        .addComponent(btnReiniciar))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblProgresso2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblProgresso1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblVida1)
                            .addComponent(lblVida2)))
                    .addComponent(btnConcentrar))
                .addContainerGap(135, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel1)
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblVida1)
                    .addComponent(lblProgresso1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblVida2)
                    .addComponent(lblProgresso2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnApanhar)
                    .addComponent(btnReiniciar))
                .addGap(18, 18, 18)
                .addComponent(btnConcentrar)
                .addGap(37, 37, 37)
                .addComponent(lblResultado)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public Integer gerarRandom() {
        Integer numeroAleatorio = ThreadLocalRandom.current().nextInt(1, 3);
        return numeroAleatorio;
    }

    public void atualizarBarraDeVida(JProgressBar barra, Integer vida) {
        barra.setValue(vida);
    }

    public void atualizarPorcentagem(JLabel label, Integer vida) {
        label.setText(vida.toString() + "%");
    }

    public void analisarCampeao() {
        String resultado;

        if (vida1 <= 0) {
            lblResultado.setText("O jogador 1 perdeu!");
            finalizarGame();
        } else if (vida2 <= 0) {
            lblResultado.setText("O jogador 2 perdeu!");
            finalizarGame();
        
        }
    }
    
    public void finalizarGame(){
            removerBotão(btnApanhar);
            removerBotão(btnConcentrar);
            mostrarBotao(btnReiniciar);
            btnApanhar.setText("");
            btnConcentrar.setText("");
            btnReiniciar.setText("Reiniciar");
    }
    
    public void removerBotão(JButton button){
         button.setOpaque(false);
        button.setContentAreaFilled(false);
        button.setBorderPainted(false);
    }
    
    public void mostrarBotao(JButton button){
        button.setOpaque(true);
        button.setContentAreaFilled(true);
        button.setBorderPainted(true);
    }

    public void reiniciarJogo() {
        lblResultado.setText("Resultado");
        vida1 = 100;
        vida2 = 100;
        atualizarBarraDeVida(lblProgresso1, vida1);
        atualizarPorcentagem(lblVida1, vida1);
        atualizarBarraDeVida(lblProgresso2, vida2);
        atualizarPorcentagem(lblVida2, vida2);
        mostrarBotao(btnApanhar);
        mostrarBotao(btnConcentrar);
        removerBotão(btnReiniciar);
        btnReiniciar.setText("");
        btnConcentrar.setText("Concentrar força");
        btnApanhar.setText("Apanhar");
    }

    private void btnApanharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApanharActionPerformed

        Integer escolhido = gerarRandom();
        if (escolhido == 1) {
            vida1 -= 10;
            atualizarBarraDeVida(lblProgresso1, vida1);
            atualizarPorcentagem(lblVida1, vida1);
            analisarCampeao();
        } else {
            vida2 -= 10;
            atualizarBarraDeVida(lblProgresso2, vida2);
            atualizarPorcentagem(lblVida2, vida2);
            analisarCampeao();
        }

    }//GEN-LAST:event_btnApanharActionPerformed

    private void btnConcentrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConcentrarActionPerformed
        Integer escolhido = gerarRandom();

        if (escolhido == 1) {
            if (vida1 > 0 && vida1 <= 98) {
                vida1 += 2;
                atualizarBarraDeVida(lblProgresso1, vida1);
                atualizarPorcentagem(lblVida1, vida1);
            }
        } else {
            if (vida2 > 0 && vida2 <= 98) {
                vida2 += 2;
                atualizarBarraDeVida(lblProgresso2, vida2);
                atualizarPorcentagem(lblVida2, vida2);

            }

        }
    }//GEN-LAST:event_btnConcentrarActionPerformed

    private void btnReiniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReiniciarActionPerformed
        // TODO add your handling code here:
        
        reiniciarJogo();
    }//GEN-LAST:event_btnReiniciarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Lutadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Lutadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Lutadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Lutadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Lutadores().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnApanhar;
    private javax.swing.JButton btnConcentrar;
    private javax.swing.JButton btnReiniciar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JProgressBar lblProgresso1;
    private javax.swing.JProgressBar lblProgresso2;
    private javax.swing.JLabel lblResultado;
    private javax.swing.JLabel lblVida1;
    private javax.swing.JLabel lblVida2;
    // End of variables declaration//GEN-END:variables
}
